import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import App from './pages/App'
import reportWebVitals from './reportWebVitals'

const Home: NextPage = () => {
  return  <>
    {/* <div className={styles.container}> */}
      <Head>
        <title>Nussara &apos;Firn&apos; Tieanklin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={styles.main}> */}
        <App />
      {/* </main> */}
    {/* </div> */}
  </>;
}

reportWebVitals();

export default Home
