# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Publish Site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Install Node dependencies
      run: npm ci
      
    - name: Build
      run: npm run build && npm run export && touch ./out/.nojekyll

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: out # The folder the action should deploy.
