import Head from 'next/head';
import React from 'react';
import NavBar from './nav-bar';
import Social from './social';

type PageProps = {
  title: string;
  children: React.ReactNode;
}

function Page({title, children}: PageProps) {
  return <>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="App">
      <NavBar />
      <Social />
      {children}
    </div>
  </>;
}

export default Page;